.github/workflows/ci.yml
The CI includes a step that installs dependencies.
However I don't think that they are needed and it also happens AFTER the code has been built and unit-tests have been run.
Fixes # (issue).
Testing with this PR...
=> remove unneded dependencies step from CI

irobot_create_control/config/control.yaml, irobot_create_control/launch/include/control.py
This PR prevents a couple of warnings from appearing when launching the simulation:
- Fixes ".py" deprecated warning
- Fixes diffdrive slower than gazebo update rate warning
=> Fixes two warnings

irobot_create_toolbox/include/irobot_create_toolbox/kidnap_estimator_publisher.hpp, irobot_create_toolbox/include/irobot_create_toolbox/robot_state.hpp, irobot_create_toolbox/src/kidnap_estimator_publisher.cpp
This changes the kidnap status callback implementation using a lambda function. 
Solves item 4 of #106.
Launch the robot using an empty world
``` #bash
ros2 launch irobot_create_gazebo create3.launch.py 
```
in a new terminal source and check that the kidnap status works as expected. The robot is consider kidnapped if both wheel drops and the four cliff sensors are activated. 
``` #bash
. install/local_setup.bash
ros2 topic echo /kidnap_status
```
=> Implements the kidnap status using lambda functions.

irobot_create_toolbox/src/kidnap_estimator_publisher.cpp
Signed-off-by: Emiliano Borghi <creativa_eborghi@irobot.com>
This PR fixes a compilation stderr in the kidnap estimator node introduced in #128.
```
--- stderr: irobot_create_toolbox                                           
/catkin_ws/src/create3_sim/irobot_create_toolbox/src/kidnap_estimator_publisher.cpp: In member function ‘void irobo
t_create_toolbox::KidnapEstimator::kidnap_callback(irobot_create_msgs::msg::HazardDetectionVector_<std::allocator<v
oid> >::SharedPtr)’:       
/catkin_ws/src/create3_sim/irobot_create_toolbox/src/kidnap_estimator_publisher.cpp:58:54: warning: comparison of i
nteger expressions of different signedness: ‘long int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-c
ompare]
58 |   kidnap_status_msg_.is_kidnapped = wheel_drop_count >= …
```
=> Fix stderr for kidnap estimator node

irobot_create_common_bringup/launch/dock_description.launch.py, irobot_create_common_bringup/launch/robot_description.launch.py, irobot_create_description/urdf/create3.urdf.xacro, irobot_create_description/urdf/dock/standard_dock.urdf.xacro, irobot_create_gazebo_bringup/launch/create3_gazebo.launch.py
- Added argument to dock_description.launch.py and robot_description.launch.py to enable/disable the visualization of cliff sensors on the robot and ir_emmiters on the dock.
- Modified create3.urdf.xacro and standard_dock.urdf.zacro to receive arguments.
Fixes #100 .
To enable visualization rays, run:
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py visulize_rays:=true
```
It should look like:
To disable visualization rays, run:
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py visulize_rays:=false
```
It should look like:
=> Add Launch arguments to enable/disable visualization of rays

.github/CODEOWNERS
Make the iRobot team (Alberto & Justin) codeowners of the repository.
This also fixes a bug where multiple codeowners rules were overwriting each others, resulting in only the last one to be applied
No tests
=> update codeowners file to make irobot team owners

dependencies.repos, irobot_create_common/irobot_create_control/package.xml
This PR removes some dependencies that were being built from sources.
All the required changes are now merged into the galactic released versions, so build from sources it's not necessary anymore.
Fixes https://github.com/iRobotEducation/create3_sim/issues/149
This does not affect the Gazebo ignition version.
Tested basic actions in empty world verifying that the robot was not rocking up while moving.
=> remove ros-control packages built from sources

README.md, dependencies.repos, irobot_create_common/irobot_create_common_bringup/launch/create3_nodes.launch.py, irobot_create_common/irobot_create_control/launch/include/control.py, irobot_create_common/irobot_create_control/package.xml, irobot_create_common/irobot_create_description/urdf/create3.urdf.xacro, irobot_create_common/irobot_create_description/urdf/wheel.urdf.xacro, irobot_create_ignition/irobot_create_ignition_bringup/launch/create3_ros_ignition_bridge.launch.py
Signed-off-by: ahcorde <ahcorde@gmail.com>
Use ign_ros2_control
This PR try to provide the same diff drive controller to Gazebo classic and Ignition simulations
```bash
ros2 launch irobot_create_ignition_bringup create3_ignition.launch.py
```
=> Use ign_ros2_control

irobot_create_common/irobot_create_description/urdf/create3.urdf.xacro, irobot_create_ignition/irobot_create_ignition_bringup/launch/create3_ros_ignition_bridge.launch.py
Added back the pose publisher plugin and bridge that were removed in #148. These are necessary for docking in ignition.
```bash
ros2 launch irobot_create_ignition_bringup create_ignition.launch.py
```
=> Added pose publisher

irobot_create_common/irobot_create_nodes/src/hazards_vector_publisher.cpp, irobot_create_common/irobot_create_nodes/src/ir_intensity_vector_publisher.cpp, irobot_create_common/irobot_create_nodes/src/kidnap_estimator_publisher.cpp, irobot_create_common/irobot_create_nodes/src/motion_control/docking_behavior.cpp, irobot_create_common/irobot_create_nodes/src/motion_control_node.cpp, irobot_create_common/irobot_create_nodes/src/robot_state.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_bumper.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_cliff_sensor.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_docking_status.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_imu.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_ir_intensity_sensor.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_ir_opcode.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_optical_mouse.cpp, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_wheel_drop.cpp
This PR is to ensure compatibility with some subscribers making reliable as QoS's default for publishers. 
Fixes issue #135  
More information [here](https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1224).
Before apply any changes I run `gazebo create3 simulation` 
```
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py
```
And then I verify the `QoS profile` of certains topics with 
```
ros2 topic info <topic> -v
```
So, before applying any changes the `Reliability` field inside `QoS profile` is `BEST_EFFORT`.
After applying the changes the same field change to `RELIABLE`
Also I run the example described [here](https://github.com/iRobotEducation/create3_examples/tree/galactic/create3_examples_py) before and after making changes and everything works as expected.
=> Reliable QoS for publishers

.github/workflows/ci.yml, dependencies.repos
Fixes CI currently broken after the update of `ign_ros2_control`.
No tests, waiting for CI to run.
=> fix CI by exporting ignition env variable

irobot_create_common/irobot_create_description/urdf/create3.urdf.xacro, irobot_create_common/irobot_create_description/urdf/dock/standard_dock.urdf.xacro, irobot_create_gazebo/irobot_create_gazebo_bringup/launch/create3_gazebo.launch.py, irobot_create_ignition/irobot_create_ignition_bringup/launch/create3_ignition.launch.py
Switching to package:// allows the description to be used by a remote computer as the mesh paths become relative rather than absolute.
Changes:
- Set GAZEBO_MODEL_URI to empty string to prevent model downloads.
- Added /usr/share/gazebo-11/models/ to GAZEBO_MODEL_PATH to use local ground plane and sun models.
- Using package:// instead of file:// for mesh paths.
```bash
ros2 launch package launch.py
```
=> Use package:// to reference meshes

dependencies.repos
remove ignition-ros2-control from dependencies.repos this is now available via rosdep
This PR re-introduces the changes proposed in https://github.com/iRobotEducation/create3_sim/pull/169 now that `ignition-ros2-control` has been officially released.
Fixes # (issue).
Check that `rosdep install --from-path src -yi` now installs `ros-galactic-ign-ros2-control (0.4.0-1focal.20220319.052953)`
=> remove ignition-ros2-control from dependencies.repos

irobot_create_common/irobot_create_nodes/CMakeLists.txt, irobot_create_common/irobot_create_nodes/package.xml, irobot_create_gazebo/irobot_create_gazebo_plugins/src/gazebo_ros_bumper.cpp
This PR fixes a bug related to the boost library.
`boost::optional` is used by the `irobot_create_nodes` library so it need to be explicitly listed as a dependency.
`boost` was also used in `gazebo_ros_bumper.cpp`, but here I think it's better to just use the std library.
None
=> add boost as explicit dependency and remove unnneded boost usage

irobot_create_gazebo/irobot_create_gazebo_bringup/launch/create3_gazebo_aws_small.launch.py
Please include a summary of the change and which issue is fixed. Also, include relevant motivation and context.
The GAZEBO_MODEL_PATH for the aws-robomaker-small-house-world models folder was not being set properly since between path `:` was missing. 
Fixes # (issue).
The PR fixes the above issue
- [x ] Bug fix (non-breaking change which fixes an issue)
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce. Also, list any relevant details for your test configuration.
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo_aws_small.launch.py
```
- [ *] I have performed a self-review of my own code
=> fix setting environment variable GAZEBO_MODEL_PATH for aws models

irobot_create_ignition/irobot_create_ignition_toolbox/CMakeLists.txt
Renamed toolbox libraries to prevent naming overlap with other packages. For example Nav2 AMCL has a `sensors_lib` too. https://github.com/ros-planning/navigation2/blob/main/nav2_amcl/CMakeLists.txt
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce. Also list any relevant details for your test configuration.
```bash
colcon build --packages-select irobot_create_ignition_toolbox
```
=> Renamed Ignition Toolbox libraries

irobot_create_common/irobot_create_control/package.xml, irobot_create_common/irobot_create_description/package.xml, irobot_create_gazebo/irobot_create_gazebo_bringup/package.xml, irobot_create_gazebo/irobot_create_gazebo_sim/package.xml, irobot_create_ignition/irobot_create_ignition_bringup/package.xml, irobot_create_ignition/irobot_create_ignition_sim/package.xml
Fixes dependency tree of the various packages.
In particular this allows to install `irobot_create_description` without pulling in gazebo.
I haven't tested it yet
=> fix dependency tree of create 3 sim packages

irobot_create_gazebo/irobot_create_gazebo_bringup/CMakeLists.txt, irobot_create_gazebo/irobot_create_gazebo_bringup/package.xml, irobot_create_ignition/irobot_create_ignition_bringup/package.xml, irobot_create_ignition/irobot_create_ignition_plugins/package.xml
make gazebo classic and ignition build time dependency if they are needed by CMakeLists.txt
Fixes problems during debian build of packages
=> make gazebo classic and ignition build time dependency 

irobot_create_common/irobot_create_common_bringup/package.xml
add missing dependency to irobot-create-common-bringup
without it, installing `irobot-create-gazebo-sim` or `irobot-create-ignition-sim` misses installing the `irobot-create-nodes` package which is actually required at runtime
=> add missing dependency to irobot-create-common-bringup

irobot_create_common/irobot_create_description/urdf/create3.urdf.xacro
Default odom topic in `diffdrive_controller` was changed in humble from `/odom` to `~/odom`.
Added a remap to revert back to using `/odom` for compatibility with `motion_control_node` and `robot_state`.
Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce. Also list any relevant details for your test configuration.
```bash
ros2 launch irobot_create_ignition_bringup create3_ignition.launch.py
```
=> Remap odom topic

.github/workflows/ci.yml
add workflow_dispatch label to CI to allow for manual triggers
=> add workflow_dispatch label to CI to allow for manual triggers

irobot_create_common/irobot_create_description/package.xml
Adds `irobot_create_description`'s dependency to `irobot_create_control`.  PR #171 was already merged but somehow this was reverted.
Fixes # (issue).
`package not found: "package 'irobot_create_control' not found, searching: ['/opt/ros/humble']"`
Cf. #171.
=> Add dependencies to `irobot_create_common`

irobot_create_common/irobot_create_nodes/include/irobot_create_nodes/wheels_publisher.hpp, irobot_create_common/irobot_create_nodes/src/wheels_publisher.cpp
I am trying to create my own odometry filter and I was using the simulation when I noticed that the ticks values were wrong.
In the code, file `irobot_create_nodes\src\wheels_publisher.cpp`, lines 79 and 82:
$$
\text{Ticks}_L = \frac{\theta_L}{2  \pi  r} \times 508.8~~~~ \text{Ticks}_R = \frac{\theta_R}{2  \pi  r} \times 508.8
$$ 
The correct formula is:
$$
\text{Ticks}_L = \frac{\theta_L}{2  \pi} \times 508.8~~~~ \text{Ticks}_R = \frac{\theta_R}{2  \pi} \times 508.8
$$
Without the $r$...
I ran the simulation and compared the wheels rotation reported by the `dynamic_joint_states` topic and the wheels rotation calculated by the formula:
$$
\theta_{L|R} = \frac{\text{Ticks}_{L|R}}{508.8} \times 2\pi
$$
```bash
ros2 launch irobot_create_gazebo_bringup create3_gazebo.launch.py 
ros2 launch …
```
=> Wheel Ticks calculation code equation correction

irobot_create_gz/irobot_create_gz_plugins/package.xml
back to what was used before, but as depend rather than buildtool_depend
=> replace gz-gui8 with gz_gui_vendor

irobot_create_common/irobot_create_control/launch/include/control.py
It looks like the latest ros_controllers release has a default timeout that's too short to allow Gazebo to properly start up, resulting in the diff drive controller & joint state broadcaster to time-out rather than starting up.  Adding an explicit timeout appears to work around this issue.
Tested locally on Jazzy.
Result before patch: diff drive controller & joint state broadcaster show timeout errors after 0.3s.
Result after patch: both controllers start normally, even when loading a complex world on a RAM-constrained laptop.
```bash
ros2 launch irobot_create_gz_bringup create3_gz.launch.py
```
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
=> Add 30s timeout for controller spawners
